language: ruby
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
gemfile:
  - test/gemfiles/Gemfile.rails.3.1
  - test/gemfiles/Gemfile.rails.3.2
  - test/gemfiles/Gemfile.rails.4.0
notifications:
  recipients:
    - oleg@khabarov.ca
branches:
  only:
    - master
matrix:
  allow_failures:
    - gemfile: test/gemfiles/Gemfile.rails.4.0
